# [Building a Simple Football Prediction Model](https://medium.com/geekculture/building-a-simple-football-prediction-model-using-machine-learning-f061e607bec5)

and [How to Compute Football Implied Probabilities From Bookmakers Odds](https://octosport.medium.com/how-to-compute-football-implied-probabilities-from-bookmakers-odds-bbb33ccf7c1d)

In [1]:
import warnings
warnings.filterwarnings('ignore')

import sqlite3
import pandas as pd
from datetime import *
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from logistic_model import LogisticRegression, LogisticModel
from implied import ImpliedProbability
from sklearn.metrics import plot_confusion_matrix, accuracy_score

In [2]:
def connect_database(db):
    con = sqlite3.connect(db)
    cursor = con.cursor()
    return cursor, con


def leer_partidos(con):
    partidos = pd.read_sql_query('SELECT * FROM partidos', con) #, index_col='fecha')
    return partidos

cur, con = connect_database('../../Clasificacion.db')

partidos = leer_partidos(con)

In [3]:
partidos['timestamp'] = partidos['timestamp'].map(lambda X: datetime.fromtimestamp(int(X)).date())
partidos['fecha'] = partidos['timestamp']
partidos = partidos.sort_values(by='fecha')

In [4]:
partidos[(partidos['temporada']=='2021-22') & (partidos['jornada']==8)]

id_partido temporada  division  jornada        equipo_local  \
39750       39837   2021-22         2        8        Ponferradina   
39856       39742   2021-22         1        8  Atletico de Bilbao   
39859       39745   2021-22         1        8               Cadiz   
39754       39841   2021-22         2        8            Alcorcon   
39753       39840   2021-22         2        8            Zaragoza   
39752       39839   2021-22         2        8              Huesca   
39751       39838   2021-22         2        8          Amorebieta   
39857       39743   2021-22         1        8             Osasuna   
39860       39746   2021-22         1        8  Atletico de Madrid   
39858       39744   2021-22         1        8            Mallorca   
39865       39751   2021-22         1        8             Granada   
39861       39747   2021-22         1        8               Elche   
39862       39748   2021-22         1        8             Espanol   
39863       39749   2021-22         1        8              Getafe   
39864       39750   2021-22         1        8          Villarreal   
39758       39845   2021-22         2        8          Las Palmas   
39757       39844   2021-22         2        8           Burgos-Cf   
39756       39843   2021-22         2        8              Malaga   
39755       39842   2021-22         2        8               Eibar   
39759       39846   2021-22         2        8             Leganes   
39760       39847   2021-22         2        8              Girona   

        equipo_visitante  goles_local  goles_visitante       fecha  \
39750         Valladolid            2                2  2021-10-01   
39856             Alaves            1                0  2021-10-01   
39859           Valencia            0                0  2021-10-02   
39754    Real Sociedad-B            1                4  2021-10-02   
39753             Oviedo            0                0  2021-10-02   
39752           Tenerife            1                2  2021-10-02   
39751  Sporting de Gijon            1                1  2021-10-02   
39857     Rayo Vallecano            1                0  2021-10-02   
39860          Barcelona            2                0  2021-10-02   
39858            Levante            1                0  2021-10-02   
39865            Sevilla            1                0  2021-10-03   
39861              Celta            1                0  2021-10-03   
39862        Real Madrid            2                1  2021-10-03   
39863      Real Sociedad            1                1  2021-10-03   
39864              Betis            2                0  2021-10-03   
39758          Cartagena            4                1  2021-10-03   
39757           Mirandes            1                0  2021-10-03   
39756        Fuenlabrada            1                0  2021-10-03   
39755      Ibiza-Eivissa            3                1  2021-10-03   
39759               Lugo            1                1  2021-10-03   
39760            Almeria            1                2  2021-10-04   

        timestamp  ...  visitante_puntos_antes  visitante_jugados_antes  \
39750  2021-10-01  ...                      10                        7   
39856  2021-10-01  ...                       3                        6   
39859  2021-10-02  ...                      11                        7   
39754  2021-10-02  ...                       6                        7   
39753  2021-10-02  ...                      10                        7   
39752  2021-10-02  ...                      11                        7   
39751  2021-10-02  ...                      16                        7   
39857  2021-10-02  ...                      13                        7   
39860  2021-10-02  ...                      12                        6   
39858  2021-10-02  ...                       4                        7   
39865  2021-10-03  ...                      14                        6   
39861  2021-10-03  ...   

In [5]:
part_test = partidos
part_test = part_test[part_test['fecha'] >= date(2021, 10, 6)] 
part_test.head(10)

id_partido temporada  division  jornada     equipo_local  \
39761       39848   2021-22         2        9       Valladolid   
39764       39851   2021-22         2        9          Almeria   
39762       39849   2021-22         2        9             Lugo   
39763       39850   2021-22         2        9         Mirandes   
39765       39852   2021-22         2        9           Oviedo   
39766       39853   2021-22         2        9  Real Sociedad-B   
39770       39857   2021-22         2        9         Tenerife   
39769       39856   2021-22         2        9      Fuenlabrada   
39768       39855   2021-22         2        9         Alcorcon   
39767       39854   2021-22         2        9        Cartagena   

        equipo_visitante  goles_local  goles_visitante       fecha  \
39761             Malaga            1                1  2021-10-08   
39764         Las Palmas            1                1  2021-10-09   
39762             Girona            1                0  2021-10-09   
39763              Eibar            3                3  2021-10-09   
39765  Sporting de Gijon            1                1  2021-10-09   
39766       Ponferradina            1                1  2021-10-10   
39770         Amorebieta            2                1  2021-10-10   
39769            Leganes            2                1  2021-10-10   
39768          Burgos-Cf            1                0  2021-10-10   
39767      Ibiza-Eivissa            5                1  2021-10-10   

        timestamp  ...  visitante_puntos_antes  visitante_jugados_antes  \
39761  2021-10-08  ...                      11                        8   
39764  2021-10-09  ...                      13                        8   
39762  2021-10-09  ...                       8                        8   
39763  2021-10-09  ...                      14                        8   
39765  2021-10-09  ...                      17                        8   
39766  2021-10-10  ...                      16                        8   
39770  2021-10-10  ...                       7                        8   
39769  2021-10-10  ...                       9                        8   
39768  2021-10-10  ...                       9                        8   
39767  2021-10-10  ...                      11                        8   

       visitante_ganados_antes  visitante_empatados_antes  \
39761                        3                          2   
39764                        3                          4   
39762                        2                          2   
39763                        4                          2   
39765                        5                          2   
39766                        5                          1   
39770                        1                          4   
39769                        2                          3   
39768                        2                          3   
39767                        2                          5   

       visitante_perdidos_antes  visitante_goles_favor_antes  \
39761                         3                            7   
39764                         1                           12   
39762                         4                            6   
39763                         2                           12   
39765                         1                           12   
39766                         2                           12   
39770                         3                            7   
39769                         3                            7   
39768                         3                            6   
39767                         1                           10   

       visitante_goles_contra_antes  visitante_racha_partidos  \
39761                            10                      None   
39764                             9                      None   
39762                             8                      None   
39763                            10

In [6]:
partidos = partidos.sort_values(by='fecha')
part_test = partidos[partidos['division'] == 1]

# Test Set
part_test = part_test[part_test['fecha'] >= date(2021, 10, 21)] 

# Train Set
partidos = partidos[partidos['fecha'] > date(2016, 8, 1)]
partidos = partidos[partidos['fecha'] < date(2021, 10, 21)]  

partidos_original = partidos

In [7]:
train = partidos.filter(['equipo_local', 'equipo_visitante', 'goles_local', 'goles_visitante'])
test = part_test.filter(['equipo_local', 'equipo_visitante', 'goles_local', 'goles_visitante'])

In [8]:
equipos = train['equipo_local'].unique()

In [9]:
test.head()

equipo_local equipo_visitante  goles_local  goles_visitante
39882               Elche          Espanol            0                0
39874  Atletico de Bilbao       Villarreal            0                0
39877              Getafe            Celta            0                0
39876               Betis   Rayo Vallecano            0                0
39879             Osasuna          Granada            0                0

## Entrenamos el Modelo

In [10]:
model = LogisticModel()

model.fit(train['equipo_local'],train['equipo_visitante'],train['goles_local'],train['goles_visitante'])

In [11]:
def result(row):
    if row['goles_local'] > row['goles_visitante']:
        return row['equipo_local']
    elif row['goles_local'] < row['goles_visitante']:
        return row['equipo_visitante']
    else:
        return 'draw'

def correct(row):
    if row['forecast_winner'] == row['real_winner']:
       return 1
    else: return 0


In [12]:
test['forecast_winner'] = test.apply(lambda row: model.predict_winner(row['equipo_local'], row['equipo_visitante']), axis=1)
test['forecast_probs'] = test.apply(lambda row: model.predict_proba(row['equipo_local'], row['equipo_visitante']), axis=1)
test['real_winner'] = test.apply(lambda row: result(row), axis=1)
test['correct'] = test.apply(lambda row: correct(row), axis=1)

In [13]:
accuracy_score(test.real_winner, test.forecast_winner)

0.1

## Extract for ELO Rating with JAX

In [14]:
jax_export = partidos_original[partidos_original['division'] == 1]
jax_export = jax_export.filter(['fecha', 'equipo_local', 'equipo_visitante', 'goles_local', 'goles_visitante'])
jax_export.rename(columns={'fecha': 'date', 'equipo_local': 'home', 'equipo_visitante': 'away', 'goles_local': 'home_goals', 'goles_visitante': 'away_goals'}, inplace=True)
jax_export.to_csv('jax_elo_dataset.csv', index=False)

In [15]:
jax_export.tail(10)

date            home      away  home_goals  away_goals
39861  2021-10-03           Elche     Celta           1           0
39864  2021-10-03      Villarreal     Betis           2           0
39866  2021-10-16         Levante    Getafe           0           0
39867  2021-10-16   Real Sociedad  Mallorca           1           0
39868  2021-10-17  Rayo Vallecano     Elche           2           1
39870  2021-10-17      Villarreal   Osasuna           1           2
39871  2021-10-17       Barcelona  Valencia           3           1
39869  2021-10-17           Celta   Sevilla           0           1
39872  2021-10-18          Alaves     Betis           0           1
39873  2021-10-18         Espanol     Cadiz           2           0

## Copa del Rey 2020-21

In [16]:
model.predict_proba('Barcelona', 'Valencia')

Valencia      draw  Barcelona
probability   0.08082  0.167257   0.751923

In [17]:
model.predict_winner('Barcelona', 'Valencia')

'Barcelona'

In [18]:
coefs = model.get_coef()
coefs.head(15)

away wins      draw  home wins
home_Alaves              -0.735698 -0.506906   0.127076
home_Albacete            -0.100594 -0.067132  -0.788215
home_Alcorcon             0.120855 -0.584575  -0.528946
home_Almeria             -0.552523 -0.408833  -0.109377
home_Amorebieta          -0.419513  0.512954  -0.756649
home_Atletico de Bilbao  -1.389957 -0.364323   0.534396
home_Atletico de Madrid  -2.425315 -0.807631   1.493554
home_Barcelona           -2.479543 -1.133026   1.782596
home_Barcelona B          0.765682 -0.543060  -1.096059
home_Betis               -0.994814 -0.588989   0.434259
home_Burgos-Cf           -0.305170 -0.071814  -0.169601
home_Cadiz               -0.814551 -0.015134  -0.306252
home_Cartagena           -0.199623 -1.018141   0.567390
home_Castellon            0.653762 -1.559620  -0.257319
home_Celta               -0.740112 -0.627393   0.240509

In [39]:
model.predict_proba('Barcelona', 'Real Madrid')

Real Madrid      draw  Barcelona
probability     0.291694  0.183434   0.524872

In [40]:
model.predict_winner('Atletico de Bilbao', 'Villarreal', )

'Atletico de Bilbao'

In [41]:
coefs = model.get_coef()

In [43]:
coefs.loc['home_Osasuna']

away wins      draw  home wins
home_Osasuna  -0.729587 -0.377976  -0.012127

In [44]:
coefs.loc['away_Granada']

away wins     draw  home wins
away_Granada  -0.584111 -0.51393  -0.032324

In [26]:
coefs.loc['home_Barcelona']

away wins      draw  home wins
home_Barcelona  -2.479543 -1.133026   1.782596

In [27]:
coefs.loc['away_Real Madrid']

away wins     draw  home wins
away_Real Madrid   1.388931 -0.53896  -1.972955

In [28]:
coefs.loc['home_Atletico de Bilbao']

away wins      draw  home wins
home_Atletico de Bilbao  -1.389957 -0.364323   0.534396

In [46]:
coefs.loc['away_Villarreal']

away wins      draw  home wins
away_Villarreal   0.490662 -0.291027  -1.102285

In [32]:
coefs.loc['away_Barcelona']['away wins']

away_Barcelona    1.384098
Name: away wins, dtype: float64

In [33]:
print(coefs.loc['away_Barcelona']['away wins'][0])
print(coefs.loc['away_Barcelona']['draw'][0])
print(coefs.loc['away_Barcelona']['home wins'][0])

1.3840977199634135
-0.5158283298870145
-2.0015859415800605


In [34]:
type(coefs.loc['away_Barcelona']['away wins'][0])

numpy.float64

## Obtener probabilidades Casas de Apuestas

In [35]:
probs = ImpliedProbability()
probs_mul = ImpliedProbability('multiplicative')
probs_add = ImpliedProbability('additive')
probs_pow = ImpliedProbability('power')
print(probs.convert(5.75, 4.20, 1.53).implied_probabilities)
print(probs_mul.convert(5.75, 4.20, 1.53).implied_probabilities)
print(probs_add.convert(5.75, 4.20, 1.53).implied_probabilities)
print(probs_pow.convert(5.75, 4.20, 1.53).implied_probabilities)

[0.15500646 0.2180107  0.62698284]
[0.16320622 0.22343708 0.6133567 ]
[0.15204536 0.21622755 0.63172709]
[0.15271821 0.21401535 0.63326645]


In [36]:
probs.convert(5.25, 4.00, 1.60).implied_probabilities

array([0.17132532, 0.22978496, 0.59888973])

In [37]:
probs.convert(5.50, 4.00, 1.57).implied_probabilities

array([0.1618835 , 0.22876829, 0.60934822])

In [38]:
probs.convert(1.75, 3.70, 4.75).implied_probabilities

array([0.55120443, 0.25386094, 0.19493462])